import Head from 'next/head';
import HomePageHeader from '../components/Headers/HomePageHeader/HomePageHeader';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <HomePageHeader />

      </div>
    </>
  )
}
